print("What is your name: ")
name = input("")
print("Your pets name: ")
pet = input("")
print ("Day in a week: ")
day = input("")
print("")
print("# Title 1 : The beginning")
print("One sunny day " + name + " walked his dog " + pet + " out in the park. To be correct and true, it was " + day + ". And he didn't know what troubles he will come to that sunny and bright " + day)